main: me.beastman3226.iq.Main
version: 1.0
depend: [Vault]
author: beastman3226
commands:
  request:
    description: Requests items.
  redeem:
    description: Redeems items.
  retrieve:
    description: Retrieves items, if any extra.